---
language: c
  #
before_install:
  # Travis runs a detached head. We need to find the current branch
  - git checkout `git branch --contains HEAD | grep -v '*'`
  # Also tags for the root(s) of the minor version(s)
  - git fetch origin --tags
  - mkdir ~/bin
  #
install:
  # Install arduino 1.6.4
  - wget http://downloads-02.arduino.cc/arduino-1.6.4-linux64.tar.xz
  - tar Jxf arduino-1.6.4-linux64.tar.xz
  - sudo mv arduino-1.6.4 /usr/local/share/arduino
  - ln -s /usr/local/share/arduino/arduino ~/bin/arduino
  # Our custom build commands
  - mv LinuxAddons/bin/*  ~/bin/
  - chmod +x ~/bin/*
  - ls -la ~/bin
  # install our platform
  - cp -r ArduinoAddons/Arduino_1.6.x/hardware/* /usr/local/share/arduino/hardware
  # copy libraries to arduino dir, as conditional includes do not work in .ino files
  - cp -r /usr/local/share/arduino/hardware/marlin/avr/libraries/* /usr/local/share/arduino/libraries/
  - cp -r ArduinoAddons/Arduino_1.6.x/libraries/* /usr/local/share/arduino/libraries/
  # add LiquidCrystal_I2C & LiquidTWI2 libraries
  - git clone https://github.com/kiyoshigawa/LiquidCrystal_I2C.git
  - mv LiquidCrystal_I2C/LiquidCrystal_I2C /usr/local/share/arduino/libraries/LiquidCrystal_I2C
  - git clone https://github.com/lincomatic/LiquidTWI2.git
  - mv LiquidTWI2 /usr/local/share/arduino/libraries/LiquidTWI2
  #
before_script:
  # arduino requires an X server even with command line
  # https://github.com/arduino/Arduino/issues/1981
  - Xvfb :1 -screen 0 1024x768x16 &> xvfb.log &
  # change back to home directory for compiling
  - cd $TRAVIS_BUILD_DIR
  #
script:
  #
  # Backup Configuration.h, Configuration_adv.h, and pins_RAMPS_14.h
  #
  - cp Marlin/Configuration.h Marlin/Configuration.h.backup
  - cp Marlin/Configuration_adv.h Marlin/Configuration_adv.h.backup
  # - cp Marlin/pins_RAMPS_14.h Marlin/pins_RAMPS_14.h.backup
  #
  # Build with the default configurations
  #
  - build_marlin
  